export const SEND_LIST = "SEND_LIST";
export const SEND_GOOGLE_INFO = "SEND_GOOGLE_INFO";
export const FETCH_LIST_ITEMS = "FETCH_LIST_ITEMS";
export const FETCH_STORE_ITEMS = "FETCH_STORE_ITEMS";
export const SET_ACTIVE_LIST = "SET_ACTIVE_LIST";
//LIST TO BE UPDATED (REDUCER)
export const SET_LIST_TO_BE_UPDATED = "SET_LIST_TO_BE_UPDATED";
export const LIST_TO_BE_UPDATED_ADD_ITEM = "LIST_TO_BE_UPDATED_ADD_ITEM";
//STORE ACTIONS
export const SET_FROM_STORE = "SET_FROM_STORE";
export const STORE_NAV = "STORE_NAV";
//PI ACTIONS
export const LIST_GET = "LIST_GET";
export const LIST_GET_ITEMS = "LIST_GET_ITEMS";
//Assign stuff
export const ASSIGN_EMPLOYEE = "ASSIGN_EMPLOYEE"