export const CREATE = "CREATE";
export const FETCH_ALL = "FETCH_ALL";
export const SEND_LIST = "SEND_LIST";
export const SEND_GOOGLE_INFO = "SEND_GOOGLE_INFO";
export const FETCH_LIST_ITEMS = "FETCH_LIST_ITEMS";
export const FETCH_STORE_ITEMS = "FETCH_STORE_ITEMS";
export const SET_ACTIVE_LIST = "SET_ACTIVE_LIST";
export const SET_LIST_TO_BE_UPDATED = "SET_LIST_TO_BE_UPDATED";
//PI ACTIONS
export const LIST_GET = "LIST_GET";
export const LIST_GET_ITEMS = "LIST_GET_ITEMS";
